name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t asmit108/ecommerce-api-node  .
      - name: Publish Image to docker hub
        run: docker push asmit108/ecommerce-api-node:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull asmit108/ecommerce-api-node:latest 
      - name: Delete old container
        run: docker rm -f ecommerce-api-node-container  
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name ecommerce-api-node-container -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} Asmit108/ecommerce-api-node:latest 